import fs from "node:fs/promises";
import path from "node:path";

/**
 * Parsers that turn Jim's local-disk sources into card intents.
 *
 * Sources today:
 *   - X:/ClaudeWork/PipBoy/briefing.html          (generated by PipBoy)
 *   - X:/ClaudeWork/<Project>/state/open-questions.md
 *
 * "Card intent" = what we want KZ to contain, not the KZ object itself.
 * The populate route takes these intents, dedupes against existing board
 * state, and calls createCard for the survivors.
 *
 * IMPORTANT: this code reads local files. It cannot run on Vercel — it is
 * only meaningful in local/dev context. The briefing→KZ push is the bridge
 * that eventually lets a Vercel-hosted ModusDaily stop caring about local
 * files, because by then KZ will be authoritative.
 */

export type CardIntent = {
  title: string;
  /** Target column title. Must match a KZ board column (resolved at populate time).
   * Briefing/state parsers only emit "Today" or "Candidates", but the standup
   * manifest may send to any column (In Progress, On Hold, Done, Context). */
  columnTitle: string;
  label: string;
  /** Why this was generated — useful for debugging / skip reasons. */
  source: string;
};

const CLAUDE_WORK_ROOT = "X:/ClaudeWork";
const BRIEFING_PATH = path.join(CLAUDE_WORK_ROOT, "PipBoy", "briefing.html");

/**
 * Parse PipBoy's briefing.html into one Today card per Next-Action bullet.
 * Pattern: each `.project-card` has a `.project-name` and a `.project-next`
 * where actions are separated by " · " (middle-dot). Split on that.
 */
export async function parseBriefing(): Promise<CardIntent[]> {
  let html: string;
  try {
    html = await fs.readFile(BRIEFING_PATH, "utf8");
  } catch {
    return [];
  }

  const intents: CardIntent[] = [];
  // Matches the sequence: open div.project-card (through .project-name)
  // and eventually a div.project-next. Non-greedy, single-line dotAll.
  const cardRe =
    /<div class="project-card[^"]*">[\s\S]*?<div class="project-name">([\s\S]*?)<\/div>[\s\S]*?<div class="project-next">\s*<strong>([\s\S]*?)<\/strong>\s*<\/div>/g;

  let match: RegExpExecArray | null;
  while ((match = cardRe.exec(html)) !== null) {
    const project = stripTags(match[1]).trim();
    const raw = stripTags(match[2]).trim();
    // "→ A · B · C" → ["A", "B", "C"]
    const actions = raw
      .replace(/^→\s*/, "")
      .split(/\s*·\s*/)
      .map((a) => a.trim())
      .filter(Boolean);
    for (const action of actions) {
      intents.push({
        title: action,
        columnTitle: "Today",
        label: project,
        source: `briefing.html → ${project}`,
      });
    }
  }
  return intents;
}

/**
 * Parse all project state/open-questions.md files we can find on disk.
 *
 * For each project directory under X:/ClaudeWork/ that has
 * `state/open-questions.md`:
 *   - Find the `## Active` section (until `## Resolved` or EOF)
 *   - Extract each `### Q{n} — {title}` heading that is NOT marked
 *     "✅ RESOLVED"
 *   - Emit one Candidates card per unresolved question
 *
 * Project label is derived from the directory name (kept humanish).
 */
export async function parseStateReports(): Promise<CardIntent[]> {
  const entries = await fs.readdir(CLAUDE_WORK_ROOT, { withFileTypes: true });
  const intents: CardIntent[] = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const qPath = path.join(
      CLAUDE_WORK_ROOT,
      entry.name,
      "state",
      "open-questions.md"
    );
    let md: string;
    try {
      md = await fs.readFile(qPath, "utf8");
    } catch {
      continue;
    }

    const label = prettifyProjectName(entry.name);
    const active = extractSection(md, "Active");
    if (!active) continue;

    // Each Q as `### Q<n> — <title>` (dash variants: — or -)
    const qRe = /^###\s+Q(\d+)\s*[—–-]\s*(.+?)\s*$/gm;
    let m: RegExpExecArray | null;
    while ((m = qRe.exec(active)) !== null) {
      const headline = m[2].trim();
      if (/✅\s*RESOLVED/i.test(headline)) continue;
      // Clean up any trailing checkbox or weirdness.
      const clean = headline.replace(/\s*#.*$/, "").trim();
      intents.push({
        title: `Q${m[1]}: ${clean}`,
        columnTitle: "Candidates",
        label,
        source: `${entry.name}/state/open-questions.md`,
      });
    }
  }
  return intents;
}

// ---------- helpers ----------

function stripTags(s: string): string {
  return s
    .replace(/<[^>]+>/g, "")
    .replace(/&middot;/g, "·")
    .replace(/&amp;/g, "&")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ");
}

function extractSection(md: string, heading: string): string | null {
  // Split on H2 boundaries ("## ..." at line start). JS regex has no \Z,
  // so we do this structurally to avoid accidents with literal characters.
  const lines = md.split(/\r?\n/);
  let inSection = false;
  const out: string[] = [];
  const target = heading.trim().toLowerCase();
  for (const line of lines) {
    const m = /^##\s+(.+?)\s*$/.exec(line);
    if (m) {
      // Entering or leaving an H2.
      const h = m[1].toLowerCase();
      // Strip trailing status markers on the heading itself ("Active", "Resolved", etc).
      if (h.startsWith(target)) {
        inSection = true;
        continue;
      }
      if (inSection) break; // Hit the next H2 — section done.
      continue;
    }
    if (inSection) out.push(line);
  }
  return out.length ? out.join("\n") : null;
}

/**
 * Best-effort human-readable label from a directory name.
 * "titanauts-mission" → "Titanauts"
 * "ModusDaily"        → "ModusDaily"
 * "Obeya Coach"       → "Obeya Coach"
 */
function prettifyProjectName(dirname: string): string {
  if (dirname === "titanauts-mission") return "Titanauts";
  if (dirname === "PipBoy") return "PipBoy";
  return dirname;
}
